### ISSUE TITLE
5.7 version does not play well with Xcode 14.0 and SwiftSyntax

### ISSUE THREAD

**Issue by fdiaz** [keith/StaticInternalSwiftSyntaxParser#2]
On Xcode Version 14.0 (14A309) and while using SwiftSyntax 0.50700.1 when running tests that depend on SwiftSyntax they fail with:

> Error: The loaded '_InternalSwiftSyntaxParser' library is from a toolchain that is not compatible with this version of SwiftSyntax

My guess is that this is caused due to [StaticInternalSwiftSyntaxParser 5.7](https://github.com/keith/StaticInternalSwiftSyntaxParser/releases/tag/5.7) being built from `Xcode 14 RC 1` and not `14A309` but I'm not entirely sure.

We were using this library's 5.6 version with Xcode 13.3.1 and SwiftSyntax 0.50600.1 and it was working appropriately.

**Comment by fdiaz** [comment]
Reading the SwiftSyntax 5.7 release it looks like this is expected https://github.com/apple/swift-syntax/releases/tag/0.50700.1

> Important: This release of SwiftSyntax is incompatible with the parser library included in the swift-5.7-RELEASE toolchain. On Linux, download a recent [swift-5.7-DEVELOPMENT-SNAPSHOT](https://www.swift.org/download/#swift-57-development) toolchain to use this SwiftSyntax version. On macOS, this version of SwiftSyntax is compatible with any recent Swift or Xcode toolchain because it includes the parser library as a binary dependency

So I'm closing this issue.

**Comment by keith** [comment]
@fdiaz that makes it sound like I should rebuild though right? our case is working so I'm a bit surprised

**Comment by fdiaz** [comment]
@keith I'm still investigating here tbh. We haven't found a workaround for this just yet. I'm asking a coworker for a small repro so we can continue investigating.

**Comment by keith** [comment]
I pushed https://github.com/keith/StaticInternalSwiftSyntaxParser/releases/tag/5.7.1 (and https://github.com/keith/swift-syntax-bazel/releases/tag/14.1.0.14B47b if you're using that too), worth trying those

**Comment by keith** [comment]
also note the:

> NOTE: With SwiftSyntax 5.6+ and Swift Package Manager, it now bundles the dynamic version of lib_InternalSwiftSyntaxParser with the library itself, leading to both this version, and that version being linked. To ignore the dynamic version pass -Xlinker -dead_strip_dylibs when building.

**Comment by fdiaz** [comment]
I think the problem I'm having is only with Intel machines. Does that make sense? Is this parser only built for m1 or does it work with universal architectures?

**Comment by keith** [comment]
It's built for both, you can see with `file path/to/binary`

**Comment by keith** [comment]
so no i wouldn't expect an issue that only affected 1

**Comment by fdiaz** [comment]
Ok, I'll try to get a minimal repro this week and see if I can figure out what's going on. Thanks for the help here!

**Comment by fdiaz** [comment]
Ok, seems like the combination of https://github.com/keith/StaticInternalSwiftSyntaxParser/releases/tag/5.7.1 and SwiftSyntax 0.50700.1 worked for me!

Thanks for the help Keith!
